//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int IdInvoice { get; set; }
        public Nullable<int> IdBooking { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> IdCreater { get; set; }
        public Nullable<bool> IsPaid { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual Receptionist Receptionist { get; set; }
    }
}
